spring.application.name=JWT-AUTHENTICATION
# Server Port
server.port=8089
server.servlet.context-path=/app
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=${JWT_SECRET}
# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update 
spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=false

# Show SQL Queries in Console
spring.jpa.show-sql=true

# Format SQL Queries
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




