name: Build and Push API Gateway Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          maven: cache

      - name: Build Jar
        run: mvn clean package -DskipTests

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t codebyarunyadav/jwt-authentication:latest .
          docker build -t codebyarunyadav/jwt-authentication:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push codebyarunyadav/jwt-authentication:latest
          docker push codebyarunyadav/jwt-authentication:${{ github.sha }}
